### ISSUE TITLE
I got error when I use it

### ISSUE THREAD

**Issue by aeiouccdd** [Plugins4Unturned/Airstrikes#1]
it doesnt work when I do /strike or /airstrike
and show the following error
[Error] MissingMethodException: Method not found: 'SDG.Unturned.DamageTool.explode'. - UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Teyhota.Airstrikes.Commands.Command_Strike:Execute(IRocketPlayer, String[])
Rocket.Core.Commands.RegisteredRocketCommand:Execute(IRocketPlayer, String[])
Rocket.Core.Commands.RocketCommandManager:Execute(IRocketPlayer, String)
Rocket.Unturned.<>c:<bindDelegates>b__16_3(SteamPlayer, String, Boolean&, Boolean&)
SDG.Unturned.ChatManager:process(SteamPlayer, String)
SDG.Unturned.ChatManager:askChat(CSteamID, Byte, String)
System.Reflection.MethodBase:Invoke(Object, Object[])
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.Provider:receiveServer(CSteamID, Byte[], Int32, Int32, Int32)
SDG.Unturned.Provider:listenServer(Int32)
SDG.Unturned.Provider:listen()
SDG.Unturned.Provider:Update()

this plugin looks good but I dont know how to fix this

**Comment by Teyhota6** [comment]
fixed with 1.2.2
